.global song_of_storms
.global song_of_storms_end
.global bolero_of_fire
.global bolero_of_fire_end
.global eponas_theme
.global eponas_theme_end
.global minuet_of_forest
.global minuet_of_forest_end
.global nocturne_of_shadow
.global nocturne_of_shadow_end
.global prelude_of_light
.global prelude_of_light_end
.global requiem_of_spirit
.global requiem_of_spirit_end
.global sarias_song
.global sarias_song_end
.global serenade_of_water
.global serenade_of_water_end
.global song_of_time
.global song_of_time_end
.global suns_song
.global suns_song_end
.global zeldas_lullaby
.global zeldas_lullaby_end
.global a_loop
.global a_loop_end
.global b_loop
.global b_loop_end
.global d_loop
.global d_loop_end
.global d2_loop
.global d2_loop_end
.global f_loop
.global f_loop_end
.global nyan_cat
.global nyan_cat_end
.global low_battery_chirp
.global low_battery_chirp_end
.global error
.global error_end

.text

bolero_of_fire:
.incbin "../data/bolero_of_fire.bin"
bolero_of_fire_end:

eponas_theme:
.incbin "../data/eponas_theme.bin"
eponas_theme_end:

minuet_of_forest:
.incbin "../data/minuet_of_forest.bin"
minuet_of_forest_end:

nocturne_of_shadow:
.incbin "../data/nocturne_of_shadow.bin"
nocturne_of_shadow_end:

prelude_of_light:
.incbin "../data/prelude_of_light.bin"
prelude_of_light_end:

requiem_of_spirit:
.incbin "../data/requiem_of_spirit.bin"
requiem_of_spirit_end:

sarias_song:
.incbin "../data/sarias_song.bin"
sarias_song_end:

serenade_of_water:
.incbin "../data/serenade_of_water.bin"
serenade_of_water_end:

song_of_time:
.incbin "../data/song_of_time.bin"
song_of_time_end:

suns_song:
.incbin "../data/suns_song.bin"
suns_song_end:

zeldas_lullaby:
.incbin "../data/zeldas_lullaby.bin"
zeldas_lullaby_end:

song_of_storms:
.incbin "../data/song_of_storms.bin"
song_of_storms_end:

a_loop:
.incbin "../data/Ocarina_A_loop.bin"
a_loop_end:

b_loop:
.incbin "../data/Ocarina_B_loop.bin"
b_loop_end:

d_loop:
.incbin "../data/Ocarina_D_loop.bin"
d_loop_end:

d2_loop:
.incbin "../data/Ocarina_D2_loop.bin"
d2_loop_end:

f_loop:
.incbin "../data/Ocarina_F_loop.bin"
f_loop_end:

nyan_cat:
.incbin "../data/nyan-cat.bin"
nyan_cat_end:

low_battery_chirp:
.incbin "../data/low_battery_chirp.bin"
low_battery_chirp_end:

error:
.incbin "../data/error.bin"
error_end: